version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: financeorg
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: 7d8jwl59
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
